### ISSUE TITLE
Can't read your code

### ISSUE THREAD

**Issue by sahithyandev** [evanfinnigan/monster_lazer#2]
I have problems with reading your code.

**Comment by evanfinnigan** [comment]
Hi @sahithyandev 

When I made this game, I didn't know JavaScript. Part of the reason I made it was to learn JavaScript. As such, the code isn't very good. It was made over a sleepless weekend at a hackathon, fueled by energy drinks.

That being said, I can try to explain it to you. Are there any parts in particular you're having trouble understanding?

The monolithic JavaScript file is full of lots of functions and hard-coded objects, but the architecture isn't very complex. The game essentially consists of a render loop and a physics loop. 

Somewhere in there is an animation system, which loops through frames of a spritesheet. The spritesheets are all normalized so all of the animations have the same number of frames, 10 I think. There is also hard-coded variables to show "Win" and "Dead" text; this is done by changing the opacity of the text. Normally, the text is invisible, but if the player dies, then the text opacity is set to 1. Somewhere during the render loop it checks whether the opacity is greater than 0 and decrements it, to fade out the message.

The laser beam always hits the closest enemy. This is done by decreasing the health of the closest enemy while the spacebar is held, as long as there is charge remaining in the laser. It is then visualized by drawing a line between the player and the enemy. When an enemies health is decreased to 0, it respawns somewhere outside the boundaries of the game. Since the enemies always move toward the player, the enemy will show up again later on.

If you have any particular questions let me know and I can try to explain more. Like I said before, it is an amateur project and isn't the best example if you're trying to learn to code.
